create table tb_genre_tags (
	id serial,
	description varchar(50) not null,
	primary key (id)
);

insert into tb_genre_tags(description) values
('Ficção'),
('Romance'),
('Fantasia'),
('Ficção-Científica'),
('Suspense/Terror'),
('Thriller'),
('Aventura'),
('Drama'),
('Polícia'),
('Comédia Romântica'),
('Ficção Histórica'),
('Infantil'),
('Épico'),
('Distopia'),
('Utopia'),
('Gótico'),
('Mitologia/Folclore'),
('Sobrenatural'),
('Sátira'),
('Humor'),
('Romance de Época'),
('Pós-Apocalíptico'),
('Viagem'),
('Natureza'),
('Ciências'),
('Educação'),
('História'),
('Artes'),
('Música'),
('Arquitetura'),
('Fotografia'),
('Tecnologia'),
('Programação'),
('Sociologia'),
('Antropologia'),
('Ciência Política'),
('Ecologia'),
('Astrologia'),
('Astronomia'),
('Esportes'),
('Gastronomia/Culinária'),
('Turismo'),
('Biografia/Autobiografia'),
('Poesia/Contos'),
('Crônicas'),
('Filosofia'),
('Autoajuda/Motivacional'),
('Religião/Espiritualidade'),
('HQs'),
('Mangás'),
('WebNovel'),
('Slice of Life'),
('Literatura Contemporânea'),
('Matemática'),
('Medicina'),
('Direito'),
('Economia'),
('Negócios'),
('Marketing'),
('Psicologia')
;